#!/usr/bin/env ansible-playbook
#
# (c) 2017 DataNexus Inc.  All Rights Reserved
---
# Build our nginx host group
- name: Create nginx host group
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars/nginx.yml
  tasks:
    # load the 'configuration file' (if one was defined) to get any variables
    # we might need during this playbook run
    - name: Load configuration file
      include_vars:
        file: "{{config_file | default('config.yml')}}"
    # if we're using dynamic provisioning; build the host groups from the
    # meta-data associated with the matching nodes in the selected cloud
    - block:
      # get a list of the node_map entries for this application
      - set_fact:
          node_map_entries: "{{node_map | selectattr('application', 'equalto', application) | list}}"
      # if more than one node_map entry was found or no matching node_map
      # entries were found, then it's an error
      - fail:
          msg: "Multiple {{application}} node_map entries found"
        when: node_map_entries | length > 1
      - fail:
          msg: "No {{application}} node_map entries found"
        when: node_map_entries | length == 0
      # build the nginx host group from existing inventory
      - include_role:
          name: build-app-host-groups
        vars:
          host_group_list:
            - name: nginx
      - set_fact:
          num_nginx_nodes: "{{groups['nginx'] | default([]) | length}}"
      # if an existing set of NGINX nodes were found, throw an error unless
      # the reuse_existing_nodes flag was set to 'true' or 'yes')
      - block:
        - name: Fail playbook run if existing nodes found and user did not request reuse
          fail:
            msg: "Found an existing set of nodes - {{(groups['nginx'] | to_yaml).split('\n').0}}; aborting playbook run"
          when: not((reuse_existing_nodes | default(false)) | bool)
        when: num_nginx_nodes | int > 0
      # if there were no NGINX nodes found, then deploy a matching set of
      # instances into the target cloud environment, ensuring that there
      # are an appropriately tagged, based on the input tags and the node_map
      # entries for this application
      - include_role:
          name: 'aws'
        when: num_nginx_nodes | int == 0 and cloud == 'aws'
      - include_role:
          name: 'osp'
        when: num_nginx_nodes == 0 and cloud == 'osp'
      when: cloud is defined and (cloud == 'aws' or cloud == 'osp')


# If we're dynamically provisioning, then do some final configuration on the
# VMs that were just launched (assuming that we're not re-using existing VMs)
- name: Complete OS configuration
  hosts: nginx
  gather_facts: yes
  vars_files:
    - vars/nginx.yml
  tasks:
    # first, initialize the play
    - include_role:
        name: initialize-play
      vars:
        gather_facts: false
        skip_network_restart: true
    # if this is a cloud deployment and we need to (re)configure nodes...
    - block:
      # then run the `preflight` role to finish the configuration of the nodes
      # that were just allocated
      - include_role:
          name: preflight
        vars:
          mountpoint: "/data"
      # and set a fact indicating that we (re)configured nodes in this play
      - set_fact:
          configured_nodes: true
      when:
        - cloud is defined and (cloud == 'aws' or cloud == 'osp')
        - ((force_node_reconfig | default(false)) | bool) or ((hostvars['localhost']['num_nginx_nodes'] | int) == 0)

# And deploy NGINX to the nodes in the `nginx` host group; note that if
# there is more than one node in the `nginx` host group, those nodes will be
# configured as a NGINX cluster (in an active-passive configuration)
- name: Install/configure NGINX server(s)
  hosts: nginx
  gather_facts: no
  vars_files:
    - vars/nginx.yml
  vars:
    - combined_package_list: "{{ (default_packages|default([])) | union(nginx_package_list) | union((install_packages_by_tag|default({})).nginx|default([])) }}"
    - nginx_nodes: "{{groups['nginx']}}"
  pre_tasks:
    # first, initialize the play
    - include_role:
        name: initialize-play
      vars:
        skip_network_restart: "{{configured_nodes | default(false)}}"
  roles:
    # now that we have all of the facts we need, provision the input nodes
    - role: nginx
