# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- set_fact:
    ngx_nodes: "{{nginx_nodes | map('extract', hostvars, [('ansible_' + api_iface), 'ipv4', 'address']) | list}}"
    num_hosts: "{{(nginx_nodes + (existing_nodes | default([]))) | length}}"
- include_tasks: install-required-packages.yml
- include_tasks: install-nginx.yml
- include_role:
    name: configure-nginx-server
- include_tasks: enable-nginx-service.yml
- include_tasks: start-nginx-service.yml
