# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- include_tasks: setup-active-passive.yml
  when: nginx_virtual_ip is defined and ((nginx_nodes | default([])) | length) > 1
- include_tasks: "configure-nginx-server.yml
- include_tasks: enable-basic-auth.yml
  when: nginx_basic_auth | bool
